# Introduction to torch

In [113]:
import torch
import numpy as np

## Tensor of ones

In [6]:
t1 = torch.ones(2,2, dtype=torch.int32)
t1

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

## Tensor of zeros

In [7]:
t2 = torch.zeros(3,3, dtype=torch.float32)
t2

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## Tensor of random numbers (uniform distribution)

In [9]:
t3 = torch.rand(2,2)
t3

tensor([[0.0893, 0.1733],
        [0.3430, 0.5918]])

## Tensor of random numbers (normal distribution)

In [10]:
t4 = torch.randn(2,2)
t4

tensor([[-0.4455,  0.0981],
        [-0.8230, -0.1729]])

## Tensor from a list of lists

In [29]:
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
y = torch.tensor([[-1, -2, -3],[-4,-5,-6],[-7,-8,-9]])

## Elementary operations on tensors

### Addition and substraction

In [18]:
z1 = x + y # use 'x - y' for substraction
z1

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [19]:
z2 = x.add(y) # use 'x.sub(y)' for substraction
z2

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [28]:
x.add_(y) # In-place addition. Use x.sub_(y) for in-place substraction

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [30]:
x.sub_(y)

tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])

In [32]:
z3 = torch.add(x, y) # use 'torch.sub(x, y) for substraction'
z3

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Multiplication and division

In [36]:
z4 = x * y # use 'x / y' for division
z4

tensor([[  -2,   -8,  -18],
        [ -32,  -50,  -72],
        [ -98, -128, -162]])

In [41]:
z5 = x / y
(x, y, z5)

(tensor([[ 2,  4,  6],
         [ 8, 10, 12],
         [14, 16, 18]]),
 tensor([[-1, -2, -3],
         [-4, -5, -6],
         [-7, -8, -9]]),
 tensor([[-2., -2., -2.],
         [-2., -2., -2.],
         [-2., -2., -2.]]))

### Mutiplication and division methods

Here are some methods for multiplication and division of tensors in PyTorch:

- `torch.matmul()`: Performs matrix multiplication on two tensors.
- `torch.mul()`: Performs element-wise multiplication on two tensors.
- `torch.Tensor.multiply()`: Multiplies a tensor by a scalar value.
- `torch.div()`: Performs element-wise division on two tensors.

Here's an example code snippet that shows how to use these methods:


```
This will output:
```
```
tensor([[19, 22],
        [43, 50]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[2, 4],
        [6, 8]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
```

Source : Conversation avec Bing, 02/06/2023

(1) [torch.matmul — PyTorch 2.0 documentation.](https://pytorch.org/docs/stable/generated/torch.matmul.html)

(2) [torch.Tensor.multiply — PyTorch 2.0 documentation.](https://pytorch.org/docs/stable/generated/torch.Tensor.multiply.html)

(3) [python - Multiply all elements of PyTorch tensor - Stack Overflow.](https://stackoverflow.com/questions/56592745/multiply-all-elements-of-pytorch-tensor)

In [141]:
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])

# Matrix multiplication
result1 = torch.matmul(tensor1, tensor2)

# Element-wise multiplication
result2 = torch.mul(tensor1, tensor2)

# Multiply a tensor by a scalar value
result3 = tensor1.multiply(2)

# Element-wise division
result4 = torch.div(tensor1, tensor2)

print(result1)
print(result2)
print(result3)
print(result4)

tensor([[19, 22],
        [43, 50]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[2, 4],
        [6, 8]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


### Retrieving data from tensors

In [43]:
x[0,0]

tensor(2)

In [44]:
x[:,0]

tensor([ 2,  8, 14])

In [45]:
x[0,:]

tensor([2, 4, 6])

#### When we want to see the actual value of a tensor element : .item() method

In [107]:
t = torch.rand(4,4, dtype=torch.float32)

In [47]:
t[0,0]

tensor(0.4988)

In [48]:
t[0,0].item() # the method '.item()' helps display all the digits of a number

0.4987754225730896

#### Resize tensors

In [66]:
t_v1 = t.view(4,4) # the argument specifies the shape of the tensor that is going to be fetched
t_v2 = t.view(2,8)
t_v3 = t.view(-1, 8) # la valeur -1 remplace une dimension que torch va déviner en prenant déjà 8 comme nombre des colonnes

In [69]:
(t_v2, t_v3)

(tensor([[0.3570, 0.4500, 0.2534, 0.5430, 0.1583, 0.2565, 0.8002, 0.7791],
         [0.1182, 0.6183, 0.2367, 0.4534, 0.7534, 0.1553, 0.1382, 0.6761]]),
 tensor([[0.3570, 0.4500, 0.2534, 0.5430, 0.1583, 0.2565, 0.8002, 0.7791],
         [0.1182, 0.6183, 0.2367, 0.4534, 0.7534, 0.1553, 0.1382, 0.6761]]))

In [70]:
t_v2.size() # size() is a method

torch.Size([2, 8])

In [71]:
t_v2.shape # shape is an attribute

torch.Size([2, 8])

In [72]:
t_v2.shape == t_v2.size()

True

#### Create a numpy.ndarray from a tensor : .numpy() method

In [108]:
# the method .numpy() converts a tensor into a numpy.ndarray class data
# the object still points to the same memory object : if one of the instance changes, the other also does.
arr = t.numpy()
print(arr,'\n', type(t),'\n', type(arr))

[[0.7927111  0.10511178 0.73489195 0.35104215]
 [0.17022473 0.02934963 0.24736589 0.37992543]
 [0.03739893 0.286771   0.1590848  0.12221432]
 [0.49257016 0.16014653 0.48293674 0.09408212]] 
 <class 'torch.Tensor'> 
 <class 'numpy.ndarray'>


In [110]:
arr

array([[0.7927111 , 0.10511178, 0.73489195, 0.35104215],
       [0.17022473, 0.02934963, 0.24736589, 0.37992543],
       [0.03739893, 0.286771  , 0.1590848 , 0.12221432],
       [0.49257016, 0.16014653, 0.48293674, 0.09408212]], dtype=float32)

In [111]:
t.add_(1)

tensor([[1.7927, 1.1051, 1.7349, 1.3510],
        [1.1702, 1.0293, 1.2474, 1.3799],
        [1.0374, 1.2868, 1.1591, 1.1222],
        [1.4926, 1.1601, 1.4829, 1.0941]])

In [112]:
arr

array([[1.792711 , 1.1051118, 1.7348919, 1.3510422],
       [1.1702247, 1.0293496, 1.247366 , 1.3799255],
       [1.0373989, 1.286771 , 1.1590848, 1.1222143],
       [1.4925702, 1.1601465, 1.4829367, 1.0940821]], dtype=float32)

#### Create a tensor from numpy.ndarray : .from_numpy() method

In [127]:
a = np.ones((3,3))
a.dtype
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [121]:
b = torch.from_numpy(a)
b.dtype
print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [132]:
# if we modify the array, the same applies to the tensor automatically
a += 1 # here we modify the array
b # here the tensor has undergone the same changes

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]], dtype=torch.float64)

#### Using GPU with CUDA for computation would look like this

In [135]:
# example
"""
if torch.cuda.is_available():
    # specify the kind of device we want to bring the tensor to
    device = torch.device('cuda')
    # create and place the tensor on the GPU
    x = torch.ones(5, device=device)
    # create a tensor
    y = torch.ones(5)
    # move the tensor to the GPU
    y = y.to(device)
    # if we want to move the tensor back to the CPU
    y = y.to('cpu')
"""

"\nif torch.cuda.is_available():\n    device = torch.device('cuda')\n    # create and place the tensor on the GPU\n    x = torch.ones(5, device=device)\n    # create a tensor\n    y = torch.ones(5)\n    # move the tensor to the GPU\n    y = y.to(device)\n    # if we want to move the tensor back to the CPU\n    y = y.to('cpu')\n"

### The 'requires_grad' key word argument

In [137]:
# This kwarg tells torch that the tensor in question will undergo gradient calculations later on
# The defalut value of this kwarg is 'False'

g = torch.rand(5, requires_grad=True)
g

tensor([0.9761, 0.6236, 0.4821, 0.2806, 0.7621], requires_grad=True)