# 11. PyTorch Tutorial 11 - Softmax and Cross Entropy

In [7]:
import numpy as np
X = np.linspace(0, 10, 9)
X = np.reshape(X, (3,3))
X

array([[ 0.  ,  1.25,  2.5 ],
       [ 3.75,  5.  ,  6.25],
       [ 7.5 ,  8.75, 10.  ]])

## Softmax function with arrays

In [14]:
# # pay attention to the kwarg 'axis' : sum of exponentials over the column vector 
Y = np.exp(X) / np.sum(np.exp(X), axis=0)
Y

array([[5.40084098e-04, 5.40084098e-04, 5.40084098e-04],
       [2.29649602e-02, 2.29649602e-02, 2.29649602e-02],
       [9.76494956e-01, 9.76494956e-01, 9.76494956e-01]])

In [16]:
Y[0,0] == np.exp(0.)/np.sum(np.exp(X[:,0])), Y[0,1] == np.exp(1.25)/np.sum(np.exp(X[:,1])), 

(True, True)

## What if I do not precise the axis? The sum takes into account all the elements of the array

In [23]:
Ybis = np.exp(X) / np.sum(np.exp(X))
Ybis

array([[3.23930535e-05, 1.13062866e-04, 3.94628178e-04],
       [1.37738768e-03, 4.80755540e-03, 1.67800171e-02],
       [5.85680146e-02, 2.04422457e-01, 7.13504484e-01]])

In [18]:
Y[0,0] == np.exp(0.)/ np.sum(np.exp(X))

True

## Softmax with torch

In [19]:
import torch

In [22]:
# pay attention to the kwarg 'dim'
T = torch.from_numpy(X)
torch.softmax(T, dim=0)

tensor([[5.4008e-04, 5.4008e-04, 5.4008e-04],
        [2.2965e-02, 2.2965e-02, 2.2965e-02],
        [9.7649e-01, 9.7649e-01, 9.7649e-01]], dtype=torch.float64)

In [24]:
T[0,0] == X[0, 0]

tensor(True)